name: robohive
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - torchrl==0.5.0
    - torch==2.4.1
    - torchvision==0.19.1
    - torchaudio==2.4.1
    - robohive==0.7.0
    - gymnasium==0.29.1
    - numpy==1.26.4
    - av==13.0.0 # Required for torchrl video recorder